// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: aarch64-registered-target

// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -O1 -Werror -emit-llvm -fenable-matrix -o - %s | FileCheck %s -check-prefix=SME
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature -sme -O1 -Werror -emit-llvm -fenable-matrix -o - -x c++ %s | FileCheck %s -check-prefix=NOSME

#define M 1
#define K 2
#define N 3

typedef __bf16 mbf16_t1 __attribute__((matrix_type(M, K)));
typedef __fp16 mfp16_t1 __attribute__((matrix_type(M, K)));
typedef float mfloat_t1 __attribute__((matrix_type(M, K)));
typedef double mdouble_t1 __attribute__((matrix_type(M, K)));
typedef signed char mschar_t1 __attribute__((matrix_type(M, K)));
typedef unsigned char muchar_t1 __attribute__((matrix_type(M, K)));
typedef signed short msshort_t1 __attribute__((matrix_type(M, K)));
typedef unsigned short mushort_t1 __attribute__((matrix_type(M, K)));
typedef signed int msint_t1 __attribute__((matrix_type(M, K)));
typedef unsigned int muint_t1 __attribute__((matrix_type(M, K)));
typedef signed long long msllong_t1 __attribute__((matrix_type(M, K)));
typedef unsigned long long mullong_t1 __attribute__((matrix_type(M, K)));

typedef __bf16 mbf16_t2 __attribute__((matrix_type(K, N)));
typedef __fp16 mfp16_t2 __attribute__((matrix_type(K, N)));
typedef float mfloat_t2 __attribute__((matrix_type(K, N)));
typedef double mdouble_t2 __attribute__((matrix_type(K, N)));
typedef signed char mschar_t2 __attribute__((matrix_type(K, N)));
typedef unsigned char muchar_t2 __attribute__((matrix_type(K, N)));
typedef signed short msshort_t2 __attribute__((matrix_type(K, N)));
typedef unsigned short mushort_t2 __attribute__((matrix_type(K, N)));
typedef signed int msint_t2 __attribute__((matrix_type(K, N)));
typedef unsigned int muint_t2 __attribute__((matrix_type(K, N)));
typedef signed long long msllong_t2 __attribute__((matrix_type(K, N)));
typedef unsigned long long mullong_t2 __attribute__((matrix_type(K, N)));

typedef __bf16 mbf16_t __attribute__((matrix_type(M, N)));
typedef __fp16 mfp16_t __attribute__((matrix_type(M, N)));
typedef float mfloat_t __attribute__((matrix_type(M, N)));
typedef double mdouble_t __attribute__((matrix_type(M, N)));
typedef signed char mschar_t __attribute__((matrix_type(M, N)));
typedef unsigned char muchar_t __attribute__((matrix_type(M, N)));
typedef signed short msshort_t __attribute__((matrix_type(M, N)));
typedef unsigned short mushort_t __attribute__((matrix_type(M, N)));
typedef signed int msint_t __attribute__((matrix_type(M, N)));
typedef unsigned int muint_t __attribute__((matrix_type(M, N)));
typedef signed long long msllong_t __attribute__((matrix_type(M, N)));
typedef unsigned long long mullong_t __attribute__((matrix_type(M, N)));

// SME-LABEL: define dso_local void @f_bf16(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x bfloat]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[A_UNPACK:%.*]] = load bfloat, ptr [[TMP0]], align 2, !tbaa [[TBAA2:![0-9]+]]
// SME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// SME-NEXT:    [[A_UNPACK4:%.*]] = load bfloat, ptr [[A_ELT3]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_UNPACK:%.*]] = load bfloat, ptr [[TMP1]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// SME-NEXT:    [[B_UNPACK7:%.*]] = load bfloat, ptr [[B_ELT6]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// SME-NEXT:    [[B_UNPACK9:%.*]] = load bfloat, ptr [[B_ELT8]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 6
// SME-NEXT:    [[B_UNPACK11:%.*]] = load bfloat, ptr [[B_ELT10]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// SME-NEXT:    [[B_UNPACK13:%.*]] = load bfloat, ptr [[B_ELT12]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 10
// SME-NEXT:    [[B_UNPACK15:%.*]] = load bfloat, ptr [[B_ELT14]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x bfloat> poison, bfloat [[A_UNPACK]], i64 0
// SME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x bfloat> [[A_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[A_UNPACK4]], i64 1
// SME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x bfloat> poison, bfloat [[B_UNPACK]], i64 0
// SME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[B_UNPACK7]], i64 1
// SME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_2_VEC_INSERT]], bfloat [[B_UNPACK9]], i64 2
// SME-NEXT:    [[B_ADDR_SROA_0_6_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_4_VEC_INSERT]], bfloat [[B_UNPACK11]], i64 3
// SME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_6_VEC_INSERT]], bfloat [[B_UNPACK13]], i64 4
// SME-NEXT:    [[B_ADDR_SROA_0_10_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_8_VEC_INSERT]], bfloat [[B_UNPACK15]], i64 5
// SME-NEXT:    [[TMP2:%.*]] = tail call <3 x bfloat> @llvm.matrix.multiply.v3bf16.v2bf16.v6bf16(<2 x bfloat> [[A_ADDR_SROA_0_2_VEC_INSERT]], <6 x bfloat> [[B_ADDR_SROA_0_10_VEC_INSERT]], i32 1, i32 2, i32 3)
// SME-NEXT:    store <3 x bfloat> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z6f_bf16u11matrix_typeILm1ELm2Eu6__bf16Eu11matrix_typeILm2ELm3Eu6__bf16E(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x bfloat]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load bfloat, ptr [[TMP0]], align 2, !tbaa [[TBAA2:![0-9]+]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load bfloat, ptr [[A_ELT3]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load bfloat, ptr [[TMP1]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load bfloat, ptr [[B_ELT6]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load bfloat, ptr [[B_ELT8]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 6
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load bfloat, ptr [[B_ELT10]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load bfloat, ptr [[B_ELT12]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 10
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load bfloat, ptr [[B_ELT14]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x bfloat> poison, bfloat [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x bfloat> [[A_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x bfloat> poison, bfloat [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_2_VEC_INSERT]], bfloat [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_6_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_4_VEC_INSERT]], bfloat [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_6_VEC_INSERT]], bfloat [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_10_VEC_INSERT:%.*]] = insertelement <6 x bfloat> [[B_ADDR_SROA_0_8_VEC_INSERT]], bfloat [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x bfloat> @llvm.matrix.multiply.v3bf16.v2bf16.v6bf16(<2 x bfloat> [[A_ADDR_SROA_0_2_VEC_INSERT]], <6 x bfloat> [[B_ADDR_SROA_0_10_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x bfloat> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mbf16_t f_bf16(mbf16_t1 a, mbf16_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_fp16(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x half]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x half>, align 8
// SME-NEXT:    call void @__sme_matmul_float2(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4:[0-9]+]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x half>, ptr [[TMP2]], align 8
// SME-NEXT:    store <3 x half> [[TMP3]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z6f_fp16u11matrix_typeILm1ELm2EDhEu11matrix_typeILm2ELm3EDhE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x half]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load half, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load half, ptr [[A_ELT3]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load half, ptr [[TMP1]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load half, ptr [[B_ELT6]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load half, ptr [[B_ELT8]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 6
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load half, ptr [[B_ELT10]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load half, ptr [[B_ELT12]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 10
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load half, ptr [[B_ELT14]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x half> poison, half [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x half> [[A_ADDR_SROA_0_0_VEC_INSERT]], half [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x half> poison, half [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x half> [[B_ADDR_SROA_0_0_VEC_INSERT]], half [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x half> [[B_ADDR_SROA_0_2_VEC_INSERT]], half [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_6_VEC_INSERT:%.*]] = insertelement <6 x half> [[B_ADDR_SROA_0_4_VEC_INSERT]], half [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x half> [[B_ADDR_SROA_0_6_VEC_INSERT]], half [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_10_VEC_INSERT:%.*]] = insertelement <6 x half> [[B_ADDR_SROA_0_8_VEC_INSERT]], half [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x half> @llvm.matrix.multiply.v3f16.v2f16.v6f16(<2 x half> [[A_ADDR_SROA_0_2_VEC_INSERT]], <6 x half> [[B_ADDR_SROA_0_10_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x half> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mfp16_t f_fp16(mfp16_t1 a, mfp16_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_float(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x float]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x float>, align 16
// SME-NEXT:    call void @__sme_matmul_float4(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x float>, ptr [[TMP2]], align 16
// SME-NEXT:    store <3 x float> [[TMP3]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z7f_floatu11matrix_typeILm1ELm2EfEu11matrix_typeILm2ELm3EfE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x float]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load float, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load float, ptr [[A_ELT3]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load float, ptr [[TMP1]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load float, ptr [[B_ELT6]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load float, ptr [[B_ELT8]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 12
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load float, ptr [[B_ELT10]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load float, ptr [[B_ELT12]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 20
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load float, ptr [[B_ELT14]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x float> poison, float [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x float> [[A_ADDR_SROA_0_0_VEC_INSERT]], float [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x float> poison, float [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x float> [[B_ADDR_SROA_0_0_VEC_INSERT]], float [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x float> [[B_ADDR_SROA_0_4_VEC_INSERT]], float [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_12_VEC_INSERT:%.*]] = insertelement <6 x float> [[B_ADDR_SROA_0_8_VEC_INSERT]], float [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x float> [[B_ADDR_SROA_0_12_VEC_INSERT]], float [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_20_VEC_INSERT:%.*]] = insertelement <6 x float> [[B_ADDR_SROA_0_16_VEC_INSERT]], float [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x float> @llvm.matrix.multiply.v3f32.v2f32.v6f32(<2 x float> [[A_ADDR_SROA_0_4_VEC_INSERT]], <6 x float> [[B_ADDR_SROA_0_20_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x float> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mfloat_t f_float(mfloat_t1 a, mfloat_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_double(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x double]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x double>, align 32
// SME-NEXT:    call void @__sme_matmul_float8(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x double>, ptr [[TMP2]], align 32
// SME-NEXT:    store <3 x double> [[TMP3]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z8f_doubleu11matrix_typeILm1ELm2EdEu11matrix_typeILm2ELm3EdE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x double]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load double, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load double, ptr [[A_ELT3]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load double, ptr [[TMP1]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load double, ptr [[B_ELT6]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load double, ptr [[B_ELT8]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 24
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load double, ptr [[B_ELT10]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 32
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load double, ptr [[B_ELT12]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 40
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load double, ptr [[B_ELT14]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x double> poison, double [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x double> [[A_ADDR_SROA_0_0_VEC_INSERT]], double [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x double> poison, double [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x double> [[B_ADDR_SROA_0_0_VEC_INSERT]], double [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x double> [[B_ADDR_SROA_0_8_VEC_INSERT]], double [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_24_VEC_INSERT:%.*]] = insertelement <6 x double> [[B_ADDR_SROA_0_16_VEC_INSERT]], double [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_32_VEC_INSERT:%.*]] = insertelement <6 x double> [[B_ADDR_SROA_0_24_VEC_INSERT]], double [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_40_VEC_INSERT:%.*]] = insertelement <6 x double> [[B_ADDR_SROA_0_32_VEC_INSERT]], double [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x double> @llvm.matrix.multiply.v3f64.v2f64.v6f64(<2 x double> [[A_ADDR_SROA_0_8_VEC_INSERT]], <6 x double> [[B_ADDR_SROA_0_40_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x double> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mdouble_t f_double(mdouble_t1 a, mdouble_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_signed_char(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i8]) align 1 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i8>, align 4
// SME-NEXT:    call void @__sme_matmul_int1(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i8>, ptr [[TMP2]], align 4
// SME-NEXT:    store <3 x i8> [[TMP3]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z13f_signed_charu11matrix_typeILm1ELm2EaEu11matrix_typeILm2ELm3EaE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i8]) align 1 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i8, ptr [[TMP0]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i8, ptr [[A_ELT3]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i8, ptr [[TMP1]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 1
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i8, ptr [[B_ELT6]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i8, ptr [[B_ELT8]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 3
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i8, ptr [[B_ELT10]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i8, ptr [[B_ELT12]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 5
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i8, ptr [[B_ELT14]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i8> poison, i8 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <2 x i8> [[A_ADDR_SROA_0_0_VEC_INSERT]], i8 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i8> poison, i8 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_0_VEC_INSERT]], i8 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_1_VEC_INSERT]], i8 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_3_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_2_VEC_INSERT]], i8 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_3_VEC_INSERT]], i8 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_5_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_4_VEC_INSERT]], i8 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i8> @llvm.matrix.multiply.v3i8.v2i8.v6i8(<2 x i8> [[A_ADDR_SROA_0_1_VEC_INSERT]], <6 x i8> [[B_ADDR_SROA_0_5_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i8> [[TMP2]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mschar_t f_signed_char(mschar_t1 a, mschar_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_unsigned_char(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i8]) align 1 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i8>, align 4
// SME-NEXT:    call void @__sme_matmul_uint1(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i8>, ptr [[TMP2]], align 4
// SME-NEXT:    store <3 x i8> [[TMP3]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z15f_unsigned_charu11matrix_typeILm1ELm2EhEu11matrix_typeILm2ELm3EhE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i8]) align 1 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i8, ptr [[TMP0]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i8, ptr [[A_ELT3]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i8, ptr [[TMP1]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 1
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i8, ptr [[B_ELT6]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i8, ptr [[B_ELT8]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 3
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i8, ptr [[B_ELT10]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i8, ptr [[B_ELT12]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 5
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i8, ptr [[B_ELT14]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i8> poison, i8 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <2 x i8> [[A_ADDR_SROA_0_0_VEC_INSERT]], i8 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i8> poison, i8 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_0_VEC_INSERT]], i8 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_1_VEC_INSERT]], i8 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_3_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_2_VEC_INSERT]], i8 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_3_VEC_INSERT]], i8 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_5_VEC_INSERT:%.*]] = insertelement <6 x i8> [[B_ADDR_SROA_0_4_VEC_INSERT]], i8 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i8> @llvm.matrix.multiply.v3i8.v2i8.v6i8(<2 x i8> [[A_ADDR_SROA_0_1_VEC_INSERT]], <6 x i8> [[B_ADDR_SROA_0_5_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i8> [[TMP2]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
muchar_t f_unsigned_char(muchar_t1 a, muchar_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_signed_short(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i16]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i16>, align 8
// SME-NEXT:    call void @__sme_matmul_int2(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i16>, ptr [[TMP2]], align 8
// SME-NEXT:    store <3 x i16> [[TMP3]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z14f_signed_shortu11matrix_typeILm1ELm2EsEu11matrix_typeILm2ELm3EsE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i16]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i16, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i16, ptr [[A_ELT3]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i16, ptr [[TMP1]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i16, ptr [[B_ELT6]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i16, ptr [[B_ELT8]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 6
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i16, ptr [[B_ELT10]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i16, ptr [[B_ELT12]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 10
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i16, ptr [[B_ELT14]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i16> poison, i16 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x i16> [[A_ADDR_SROA_0_0_VEC_INSERT]], i16 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i16> poison, i16 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_0_VEC_INSERT]], i16 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_2_VEC_INSERT]], i16 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_6_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_4_VEC_INSERT]], i16 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_6_VEC_INSERT]], i16 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_10_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_8_VEC_INSERT]], i16 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i16> @llvm.matrix.multiply.v3i16.v2i16.v6i16(<2 x i16> [[A_ADDR_SROA_0_2_VEC_INSERT]], <6 x i16> [[B_ADDR_SROA_0_10_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i16> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
msshort_t f_signed_short(msshort_t1 a, msshort_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_unsigned_short(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i16]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i16>, align 8
// SME-NEXT:    call void @__sme_matmul_uint2(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i16>, ptr [[TMP2]], align 8
// SME-NEXT:    store <3 x i16> [[TMP3]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z16f_unsigned_shortu11matrix_typeILm1ELm2EtEu11matrix_typeILm2ELm3EtE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i16]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i16, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i16, ptr [[A_ELT3]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i16, ptr [[TMP1]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 2
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i16, ptr [[B_ELT6]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i16, ptr [[B_ELT8]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 6
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i16, ptr [[B_ELT10]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i16, ptr [[B_ELT12]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 10
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i16, ptr [[B_ELT14]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i16> poison, i16 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x i16> [[A_ADDR_SROA_0_0_VEC_INSERT]], i16 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i16> poison, i16 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_0_VEC_INSERT]], i16 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_2_VEC_INSERT]], i16 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_6_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_4_VEC_INSERT]], i16 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_6_VEC_INSERT]], i16 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_10_VEC_INSERT:%.*]] = insertelement <6 x i16> [[B_ADDR_SROA_0_8_VEC_INSERT]], i16 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i16> @llvm.matrix.multiply.v3i16.v2i16.v6i16(<2 x i16> [[A_ADDR_SROA_0_2_VEC_INSERT]], <6 x i16> [[B_ADDR_SROA_0_10_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i16> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mushort_t f_unsigned_short(mushort_t1 a, mushort_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_signed_int(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i32]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i32>, align 16
// SME-NEXT:    call void @__sme_matmul_int4(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i32>, ptr [[TMP2]], align 16
// SME-NEXT:    store <3 x i32> [[TMP3]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z12f_signed_intu11matrix_typeILm1ELm2EiEu11matrix_typeILm2ELm3EiE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i32]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i32, ptr [[A_ELT3]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i32, ptr [[TMP1]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i32, ptr [[B_ELT6]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i32, ptr [[B_ELT8]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 12
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i32, ptr [[B_ELT10]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i32, ptr [[B_ELT12]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 20
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i32, ptr [[B_ELT14]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i32> poison, i32 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x i32> [[A_ADDR_SROA_0_0_VEC_INSERT]], i32 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i32> poison, i32 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_0_VEC_INSERT]], i32 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_4_VEC_INSERT]], i32 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_12_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_8_VEC_INSERT]], i32 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_12_VEC_INSERT]], i32 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_20_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_16_VEC_INSERT]], i32 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i32> @llvm.matrix.multiply.v3i32.v2i32.v6i32(<2 x i32> [[A_ADDR_SROA_0_4_VEC_INSERT]], <6 x i32> [[B_ADDR_SROA_0_20_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i32> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
msint_t f_signed_int(msint_t1 a, msint_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_unsigned_int(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i32]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i32>, align 16
// SME-NEXT:    call void @__sme_matmul_uint4(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i32>, ptr [[TMP2]], align 16
// SME-NEXT:    store <3 x i32> [[TMP3]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z14f_unsigned_intu11matrix_typeILm1ELm2EjEu11matrix_typeILm2ELm3EjE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i32]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i32, ptr [[A_ELT3]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i32, ptr [[TMP1]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 4
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i32, ptr [[B_ELT6]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i32, ptr [[B_ELT8]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 12
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i32, ptr [[B_ELT10]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i32, ptr [[B_ELT12]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 20
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i32, ptr [[B_ELT14]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i32> poison, i32 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x i32> [[A_ADDR_SROA_0_0_VEC_INSERT]], i32 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i32> poison, i32 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_0_VEC_INSERT]], i32 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_4_VEC_INSERT]], i32 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_12_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_8_VEC_INSERT]], i32 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_12_VEC_INSERT]], i32 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_20_VEC_INSERT:%.*]] = insertelement <6 x i32> [[B_ADDR_SROA_0_16_VEC_INSERT]], i32 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i32> @llvm.matrix.multiply.v3i32.v2i32.v6i32(<2 x i32> [[A_ADDR_SROA_0_4_VEC_INSERT]], <6 x i32> [[B_ADDR_SROA_0_20_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i32> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
muint_t f_unsigned_int(muint_t1 a, muint_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_signed_long_long(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i64]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i64>, align 32
// SME-NEXT:    call void @__sme_matmul_int8(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i64>, ptr [[TMP2]], align 32
// SME-NEXT:    store <3 x i64> [[TMP3]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z18f_signed_long_longu11matrix_typeILm1ELm2ExEu11matrix_typeILm2ELm3ExE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i64]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i64, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i64, ptr [[A_ELT3]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i64, ptr [[TMP1]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i64, ptr [[B_ELT6]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i64, ptr [[B_ELT8]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 24
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i64, ptr [[B_ELT10]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 32
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i64, ptr [[B_ELT12]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 40
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i64, ptr [[B_ELT14]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i64> poison, i64 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x i64> [[A_ADDR_SROA_0_0_VEC_INSERT]], i64 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i64> poison, i64 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_0_VEC_INSERT]], i64 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_8_VEC_INSERT]], i64 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_24_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_16_VEC_INSERT]], i64 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_32_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_24_VEC_INSERT]], i64 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_40_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_32_VEC_INSERT]], i64 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i64> @llvm.matrix.multiply.v3i64.v2i64.v6i64(<2 x i64> [[A_ADDR_SROA_0_8_VEC_INSERT]], <6 x i64> [[B_ADDR_SROA_0_40_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i64> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
msllong_t f_signed_long_long(msllong_t1 a, msllong_t2 b) {
  return a * b;
}

// SME-LABEL: define dso_local void @f_unsigned_long_long(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i64]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]], ptr noundef [[TMP1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP2:%.*]] = alloca <3 x i64>, align 32
// SME-NEXT:    call void @__sme_matmul_uint8(ptr nonnull [[TMP2]], ptr [[TMP0]], ptr [[TMP1]], i32 1, i32 2, i32 3) #[[ATTR4]]
// SME-NEXT:    [[TMP3:%.*]] = load <3 x i64>, ptr [[TMP2]], align 32
// SME-NEXT:    store <3 x i64> [[TMP3]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z20f_unsigned_long_longu11matrix_typeILm1ELm2EyEu11matrix_typeILm2ELm3EyE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([3 x i64]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]], ptr nocapture noundef readonly [[TMP1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i64, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT3:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK4:%.*]] = load i64, ptr [[A_ELT3]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_UNPACK:%.*]] = load i64, ptr [[TMP1]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT6:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 8
// NOSME-NEXT:    [[B_UNPACK7:%.*]] = load i64, ptr [[B_ELT6]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT8:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 16
// NOSME-NEXT:    [[B_UNPACK9:%.*]] = load i64, ptr [[B_ELT8]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT10:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 24
// NOSME-NEXT:    [[B_UNPACK11:%.*]] = load i64, ptr [[B_ELT10]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT12:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 32
// NOSME-NEXT:    [[B_UNPACK13:%.*]] = load i64, ptr [[B_ELT12]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[B_ELT14:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 40
// NOSME-NEXT:    [[B_UNPACK15:%.*]] = load i64, ptr [[B_ELT14]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i64> poison, i64 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x i64> [[A_ADDR_SROA_0_0_VEC_INSERT]], i64 [[A_UNPACK4]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <6 x i64> poison, i64 [[B_UNPACK]], i64 0
// NOSME-NEXT:    [[B_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_0_VEC_INSERT]], i64 [[B_UNPACK7]], i64 1
// NOSME-NEXT:    [[B_ADDR_SROA_0_16_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_8_VEC_INSERT]], i64 [[B_UNPACK9]], i64 2
// NOSME-NEXT:    [[B_ADDR_SROA_0_24_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_16_VEC_INSERT]], i64 [[B_UNPACK11]], i64 3
// NOSME-NEXT:    [[B_ADDR_SROA_0_32_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_24_VEC_INSERT]], i64 [[B_UNPACK13]], i64 4
// NOSME-NEXT:    [[B_ADDR_SROA_0_40_VEC_INSERT:%.*]] = insertelement <6 x i64> [[B_ADDR_SROA_0_32_VEC_INSERT]], i64 [[B_UNPACK15]], i64 5
// NOSME-NEXT:    [[TMP2:%.*]] = tail call <3 x i64> @llvm.matrix.multiply.v3i64.v2i64.v6i64(<2 x i64> [[A_ADDR_SROA_0_8_VEC_INSERT]], <6 x i64> [[B_ADDR_SROA_0_40_VEC_INSERT]], i32 1, i32 2, i32 3)
// NOSME-NEXT:    store <3 x i64> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
mullong_t f_unsigned_long_long(mullong_t1 a, mullong_t2 b) {
  return a * b;
}
