// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: aarch64-registered-target

// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -O1 -Werror -emit-llvm -fenable-matrix -o - %s | FileCheck %s -check-prefix=SME
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature -sme -O1 -Werror -emit-llvm -fenable-matrix -o - -x c++ %s | FileCheck %s -check-prefix=NOSME

#define M 1
#define K 2

typedef __bf16 mbf16_t __attribute__((matrix_type(M, K)));
typedef __fp16 mfp16_t __attribute__((matrix_type(M, K)));
typedef float mfloat_t __attribute__((matrix_type(M, K)));
typedef double mdouble_t __attribute__((matrix_type(M, K)));
typedef signed char mschar_t __attribute__((matrix_type(M, K)));
typedef unsigned char muchar_t __attribute__((matrix_type(M, K)));
typedef signed short msshort_t __attribute__((matrix_type(M, K)));
typedef unsigned short mushort_t __attribute__((matrix_type(M, K)));
typedef signed int msint_t __attribute__((matrix_type(M, K)));
typedef unsigned int muint_t __attribute__((matrix_type(M, K)));
typedef signed long long msllong_t __attribute__((matrix_type(M, K)));
typedef unsigned long long mullong_t __attribute__((matrix_type(M, K)));

typedef __bf16 tran_mbf16_t __attribute__((matrix_type(K, M)));
typedef __fp16 tran_mfp16_t __attribute__((matrix_type(K, M)));
typedef float tran_mfloat_t __attribute__((matrix_type(K, M)));
typedef double tran_mdouble_t __attribute__((matrix_type(K, M)));
typedef signed char tran_mschar_t __attribute__((matrix_type(K, M)));
typedef unsigned char tran_muchar_t __attribute__((matrix_type(K, M)));
typedef signed short tran_msshort_t __attribute__((matrix_type(K, M)));
typedef unsigned short tran_mushort_t __attribute__((matrix_type(K, M)));
typedef signed int tran_msint_t __attribute__((matrix_type(K, M)));
typedef unsigned int tran_muint_t __attribute__((matrix_type(K, M)));
typedef signed long long tran_msllong_t __attribute__((matrix_type(K, M)));
typedef unsigned long long tran_mullong_t __attribute__((matrix_type(K, M)));

// SME-LABEL: define dso_local void @f_bf16(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x bfloat]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[A_UNPACK:%.*]] = load bfloat, ptr [[TMP0]], align 2, !tbaa [[TBAA2:![0-9]+]]
// SME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// SME-NEXT:    [[A_UNPACK3:%.*]] = load bfloat, ptr [[A_ELT2]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x bfloat> poison, bfloat [[A_UNPACK]], i64 0
// SME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x bfloat> [[A_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[A_UNPACK3]], i64 1
// SME-NEXT:    [[TMP1:%.*]] = tail call <2 x bfloat> @llvm.matrix.transpose.v2bf16(<2 x bfloat> [[A_ADDR_SROA_0_2_VEC_INSERT]], i32 1, i32 2)
// SME-NEXT:    store <2 x bfloat> [[TMP1]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z6f_bf16u11matrix_typeILm1ELm2Eu6__bf16E(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x bfloat]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load bfloat, ptr [[TMP0]], align 2, !tbaa [[TBAA2:![0-9]+]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load bfloat, ptr [[A_ELT2]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x bfloat> poison, bfloat [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x bfloat> [[A_ADDR_SROA_0_0_VEC_INSERT]], bfloat [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x bfloat> @llvm.matrix.transpose.v2bf16(<2 x bfloat> [[A_ADDR_SROA_0_2_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x bfloat> [[TMP1]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mbf16_t f_bf16(mbf16_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_fp16(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x half]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x half>, align 4
// SME-NEXT:    call void @__sme_transpose_float2(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4:[0-9]+]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x half>, ptr [[TMP1]], align 4
// SME-NEXT:    store <2 x half> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z6f_fp16u11matrix_typeILm1ELm2EDhE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x half]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load half, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load half, ptr [[A_ELT2]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x half> poison, half [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x half> [[A_ADDR_SROA_0_0_VEC_INSERT]], half [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x half> @llvm.matrix.transpose.v2f16(<2 x half> [[A_ADDR_SROA_0_2_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x half> [[TMP1]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mfp16_t f_fp16(mfp16_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_float(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x float]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x float>, align 8
// SME-NEXT:    call void @__sme_transpose_float4(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x float>, ptr [[TMP1]], align 8
// SME-NEXT:    store <2 x float> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z7f_floatu11matrix_typeILm1ELm2EfE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x float]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load float, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load float, ptr [[A_ELT2]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x float> poison, float [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x float> [[A_ADDR_SROA_0_0_VEC_INSERT]], float [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x float> @llvm.matrix.transpose.v2f32(<2 x float> [[A_ADDR_SROA_0_4_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x float> [[TMP1]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mfloat_t f_float(mfloat_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_double(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x double]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x double>, align 16
// SME-NEXT:    call void @__sme_transpose_float8(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x double>, ptr [[TMP1]], align 16
// SME-NEXT:    store <2 x double> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z8f_doubleu11matrix_typeILm1ELm2EdE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x double]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load double, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load double, ptr [[A_ELT2]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x double> poison, double [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x double> [[A_ADDR_SROA_0_0_VEC_INSERT]], double [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x double> @llvm.matrix.transpose.v2f64(<2 x double> [[A_ADDR_SROA_0_8_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x double> [[TMP1]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mdouble_t f_double(mdouble_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_signed_char(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i8]) align 1 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i8>, align 2
// SME-NEXT:    call void @__sme_transpose_int1(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i8>, ptr [[TMP1]], align 2
// SME-NEXT:    store <2 x i8> [[TMP2]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z13f_signed_charu11matrix_typeILm1ELm2EaE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i8]) align 1 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i8, ptr [[TMP0]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i8, ptr [[A_ELT2]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i8> poison, i8 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <2 x i8> [[A_ADDR_SROA_0_0_VEC_INSERT]], i8 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i8> @llvm.matrix.transpose.v2i8(<2 x i8> [[A_ADDR_SROA_0_1_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i8> [[TMP1]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mschar_t f_signed_char(mschar_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_unsigned_char(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i8]) align 1 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i8>, align 2
// SME-NEXT:    call void @__sme_transpose_int1(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i8>, ptr [[TMP1]], align 2
// SME-NEXT:    store <2 x i8> [[TMP2]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z15f_unsigned_charu11matrix_typeILm1ELm2EhE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i8]) align 1 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i8, ptr [[TMP0]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i8, ptr [[A_ELT2]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i8> poison, i8 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_1_VEC_INSERT:%.*]] = insertelement <2 x i8> [[A_ADDR_SROA_0_0_VEC_INSERT]], i8 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i8> @llvm.matrix.transpose.v2i8(<2 x i8> [[A_ADDR_SROA_0_1_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i8> [[TMP1]], ptr [[AGG_RESULT]], align 1, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_muchar_t f_unsigned_char(muchar_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_signed_short(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i16]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i16>, align 4
// SME-NEXT:    call void @__sme_transpose_int2(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i16>, ptr [[TMP1]], align 4
// SME-NEXT:    store <2 x i16> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z14f_signed_shortu11matrix_typeILm1ELm2EsE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i16]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i16, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i16, ptr [[A_ELT2]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i16> poison, i16 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x i16> [[A_ADDR_SROA_0_0_VEC_INSERT]], i16 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.matrix.transpose.v2i16(<2 x i16> [[A_ADDR_SROA_0_2_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i16> [[TMP1]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_msshort_t f_signed_short(msshort_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_unsigned_short(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i16]) align 2 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i16>, align 4
// SME-NEXT:    call void @__sme_transpose_int2(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i16>, ptr [[TMP1]], align 4
// SME-NEXT:    store <2 x i16> [[TMP2]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z16f_unsigned_shortu11matrix_typeILm1ELm2EtE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i16]) align 2 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i16, ptr [[TMP0]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 2
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i16, ptr [[A_ELT2]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i16> poison, i16 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_2_VEC_INSERT:%.*]] = insertelement <2 x i16> [[A_ADDR_SROA_0_0_VEC_INSERT]], i16 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.matrix.transpose.v2i16(<2 x i16> [[A_ADDR_SROA_0_2_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i16> [[TMP1]], ptr [[AGG_RESULT]], align 2, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mushort_t f_unsigned_short(mushort_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_signed_int(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i32]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i32>, align 8
// SME-NEXT:    call void @__sme_transpose_int4(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i32>, ptr [[TMP1]], align 8
// SME-NEXT:    store <2 x i32> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z12f_signed_intu11matrix_typeILm1ELm2EiE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i32]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i32, ptr [[A_ELT2]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i32> poison, i32 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x i32> [[A_ADDR_SROA_0_0_VEC_INSERT]], i32 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.matrix.transpose.v2i32(<2 x i32> [[A_ADDR_SROA_0_4_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i32> [[TMP1]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_msint_t f_signed_int(msint_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_unsigned_int(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i32]) align 4 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i32>, align 8
// SME-NEXT:    call void @__sme_transpose_int4(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i32>, ptr [[TMP1]], align 8
// SME-NEXT:    store <2 x i32> [[TMP2]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z14f_unsigned_intu11matrix_typeILm1ELm2EjE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i32]) align 4 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 4
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i32, ptr [[A_ELT2]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i32> poison, i32 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_4_VEC_INSERT:%.*]] = insertelement <2 x i32> [[A_ADDR_SROA_0_0_VEC_INSERT]], i32 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.matrix.transpose.v2i32(<2 x i32> [[A_ADDR_SROA_0_4_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i32> [[TMP1]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_muint_t f_unsigned_int(muint_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_signed_long_long(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i64]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i64>, align 16
// SME-NEXT:    call void @__sme_transpose_int8(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[TMP1]], align 16
// SME-NEXT:    store <2 x i64> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z18f_signed_long_longu11matrix_typeILm1ELm2ExE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i64]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i64, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i64, ptr [[A_ELT2]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i64> poison, i64 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x i64> [[A_ADDR_SROA_0_0_VEC_INSERT]], i64 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i64> @llvm.matrix.transpose.v2i64(<2 x i64> [[A_ADDR_SROA_0_8_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i64> [[TMP1]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_msllong_t f_signed_long_long(msllong_t a) {
  return __builtin_matrix_transpose(a);
}

// SME-LABEL: define dso_local void @f_unsigned_long_long(
// SME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i64]) align 8 [[AGG_RESULT:%.*]], ptr noundef [[TMP0:%.*]]) local_unnamed_addr #[[ATTR2]] {
// SME-NEXT:  [[ENTRY:.*:]]
// SME-NEXT:    [[TMP1:%.*]] = alloca <2 x i64>, align 16
// SME-NEXT:    call void @__sme_transpose_int8(ptr nonnull [[TMP1]], ptr [[TMP0]], i32 1, i32 2) #[[ATTR4]]
// SME-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[TMP1]], align 16
// SME-NEXT:    store <2 x i64> [[TMP2]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// SME-NEXT:    ret void
//
// NOSME-LABEL: define dso_local void @_Z20f_unsigned_long_longu11matrix_typeILm1ELm2EyE(
// NOSME-SAME: ptr dead_on_unwind noalias nocapture writable writeonly sret([2 x i64]) align 8 [[AGG_RESULT:%.*]], ptr nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOSME-NEXT:  [[ENTRY:.*:]]
// NOSME-NEXT:    [[A_UNPACK:%.*]] = load i64, ptr [[TMP0]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ELT2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
// NOSME-NEXT:    [[A_UNPACK3:%.*]] = load i64, ptr [[A_ELT2]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    [[A_ADDR_SROA_0_0_VEC_INSERT:%.*]] = insertelement <2 x i64> poison, i64 [[A_UNPACK]], i64 0
// NOSME-NEXT:    [[A_ADDR_SROA_0_8_VEC_INSERT:%.*]] = insertelement <2 x i64> [[A_ADDR_SROA_0_0_VEC_INSERT]], i64 [[A_UNPACK3]], i64 1
// NOSME-NEXT:    [[TMP1:%.*]] = tail call <2 x i64> @llvm.matrix.transpose.v2i64(<2 x i64> [[A_ADDR_SROA_0_8_VEC_INSERT]], i32 1, i32 2)
// NOSME-NEXT:    store <2 x i64> [[TMP1]], ptr [[AGG_RESULT]], align 8, !tbaa [[TBAA2]]
// NOSME-NEXT:    ret void
//
tran_mullong_t f_unsigned_long_long(mullong_t a) {
  return __builtin_matrix_transpose(a);
}
